#!/bin/sh

DIR="$HOME/.trash"
LOC="$DIR/trash.tar"

main() {
	while getopts ":er:" opt; do
		case $opt in
		e)
			echo "All trash cleared" >&2
			rm ~/.trash/trash.tar
			exit 0
			;;
		r)
			echo "restore $OPTARG" >&2
			exit 0
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			exit 1
			;;
		:)
			echo "-$OPTARG value required." >&2
			exit 1
			;;
		esac
	done

	if [ $# -eq 0 ]; then
		echo "Which file you decided to trash?"
		exit 1
	fi

	if [ -e "$LOC" ]; then
		echo "trash appended $@"
		tar -rf "$LOC" "$@"
	else
		echo "trash created $@"
		mkdir -p "$DIR"
		tar -cf "$LOC" "$@"
	fi

	if [ $? -eq 0 ]; then
		rm -rf "$@"
		echo "files removed"
	else
		echo "files can't removed"
		exit 1
	fi

	echo "trash done"
}

main "$@"
